import json
import os
import re
from pathlib import Path

import requests
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt


# =========================================================
# CONFIG
# =========================================================

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()

DEFAULT_MODELS = [
    "gemini-3.5-flash-lite",
    "gemini-3.6-flash",
    "gemini-3.7-flash",
    "gemini-3.8-flash",
]

GEMINI_MODELS = [
    x.strip()
    for x in os.getenv("GEMINI_MODELS", ",".join(DEFAULT_MODELS)).split(",")
    if x.strip()
]

GEMINI_URL = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    "{model}:generateContent"
)


# =========================================================
# AI PROMPT
# =========================================================

PROMPT = r"""
You are a professional presentation strategist and educational content designer.

Create a complete PowerPoint presentation based on the user's request.

USER REQUEST:
__REQUEST__

Your job:
1. Understand the topic.
2. Decide the best logical structure.
3. Create useful, accurate and engaging slide content.
4. Avoid unnecessary text.
5. Make every slide visually different when appropriate.
6. Use concise professional language.
7. If the user specifies a language, use that language.
8. If no language is specified, use the language of the user's request.
9. Do not invent statistics. If exact statistics are unknown, avoid numerical claims.
10. Make the presentation suitable for a real classroom, business meeting or public presentation.

Return ONLY valid JSON.

JSON structure:

{
  "title": "Presentation title",
  "subtitle": "Short subtitle",
  "language": "uz",
  "slides": [
    {
      "title": "Slide title",
      "layout": "bullets",
      "bullets": [
        "Short point",
        "Short point",
        "Short point"
      ]
    },
    {
      "title": "Slide title",
      "layout": "two_column",
      "left_title": "Left section",
      "left": [
        "Point",
        "Point"
      ],
      "right_title": "Right section",
      "right": [
        "Point",
        "Point"
      ]
    },
    {
      "title": "Slide title",
      "layout": "stats",
      "stats": [
        {
          "value": "01",
          "label": "Short label"
        },
        {
          "value": "02",
          "label": "Short label"
        },
        {
          "value": "03",
          "label": "Short label"
        }
      ]
    },
    {
      "title": "Slide title",
      "layout": "quote",
      "quote": "Important short statement",
      "source": "Source or author"
    }
  ]
}

Allowed layouts:
- bullets
- two_column
- stats
- quote

Rules:
- Usually create 6-10 slides unless the user requests another number.
- If the user explicitly gives a slide count, follow it.
- Do not put more than 5 bullets on one slide.
- Keep bullets short.
- Do not repeat the same information.
- The first slide is automatically generated by the application, so the "slides" array should contain the CONTENT slides only.
- Return JSON only.
"""


# =========================================================
# HELPERS
# =========================================================

def clean_json(text: str) -> str:
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    end = text.rfind("}")

    if start == -1 or end == -1:
        raise ValueError("AI returned invalid JSON.")

    return text[start:end + 1]


def extract_response_text(data: dict) -> str:
    candidates = data.get("candidates", [])

    if not candidates:
        raise RuntimeError("Gemini returned no candidates.")

    candidate = candidates[0]

    content = candidate.get("content", {})
    parts = content.get("parts", [])

    texts = []

    for part in parts:
        if isinstance(part, dict) and "text" in part:
            texts.append(part["text"])

    result = "\n".join(texts).strip()

    if not result:
        raise RuntimeError("Gemini returned an empty response.")

    return result


# =========================================================
# GEMINI
# =========================================================

def ask_gemini(request_text: str) -> dict:
    if not GEMINI_API_KEY:
        raise RuntimeError(
            "GEMINI_API_KEY is missing in the server environment."
        )

    prompt = PROMPT.replace("__REQUEST__", request_text.strip())

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [
                    {
                        "text": prompt
                    }
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json",
            "temperature": 0.7,
            "maxOutputTokens": 12000
        }
    }

    errors = []

    for model in GEMINI_MODELS:
        url = GEMINI_URL.format(model=model)

        try:
            response = requests.post(
                url,
                headers={
                    "x-goog-api-key": GEMINI_API_KEY,
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=90,
            )

            if response.status_code in (429, 500, 502, 503, 504):
                errors.append(
                    f"{model}: HTTP {response.status_code}"
                )
                continue

            response.raise_for_status()

            data = response.json()

            raw_text = extract_response_text(data)
            json_text = clean_json(raw_text)

            result = json.loads(json_text)

            if not isinstance(result, dict):
                raise ValueError("AI response is not an object.")

            slides = result.get("slides")

            if not isinstance(slides, list) or not slides:
                raise ValueError("AI did not return slides.")

            result["_model"] = model

            return result

        except requests.RequestException as exc:
            errors.append(f"{model}: {exc}")

        except (ValueError, json.JSONDecodeError, RuntimeError) as exc:
            errors.append(f"{model}: {exc}")

    raise RuntimeError(
        "AI xizmatlari vaqtincha ishlamadi.\n\n"
        + "\n".join(errors)
    )


# =========================================================
# POWERPOINT DESIGN
# =========================================================

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

BG = RGBColor(248, 249, 252)
DARK = RGBColor(22, 27, 34)
MUTED = RGBColor(92, 99, 112)
ACCENT = RGBColor(245, 102, 45)
WHITE = RGBColor(255, 255, 255)
LIGHT = RGBColor(232, 235, 240)


def add_background(slide):
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        0,
        0,
        SLIDE_W,
        SLIDE_H,
    )

    shape.fill.solid()
    shape.fill.fore_color.rgb = BG
    shape.line.fill.background()


def add_top_accent(slide):
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        0,
        0,
        Inches(0.16),
        SLIDE_H,
    )

    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT
    shape.line.fill.background()


def add_footer(slide, number):
    line = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.65),
        Inches(7.05),
        Inches(12.0),
        Inches(0.01),
    )

    line.fill.solid()
    line.fill.fore_color.rgb = LIGHT
    line.line.fill.background()

    box = slide.shapes.add_textbox(
        Inches(11.8),
        Inches(7.08),
        Inches(0.7),
        Inches(0.25),
    )

    p = box.text_frame.paragraphs[0]
    p.text = str(number)
    p.font.size = Pt(9)
    p.font.color.rgb = MUTED
    p.alignment = PP_ALIGN.RIGHT


def add_text(
    slide,
    text,
    x,
    y,
    w,
    h,
    size=20,
    bold=False,
    color=DARK,
    align=PP_ALIGN.LEFT,
):
    box = slide.shapes.add_textbox(
        x,
        y,
        w,
        h,
    )

    tf = box.text_frame
    tf.clear()
    tf.word_wrap = True
    tf.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.text = str(text)
    p.alignment = align

    p.font.name = "Aptos"
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color

    return box


def add_title(slide, title):
    add_text(
        slide,
        title,
        Inches(0.8),
        Inches(0.55),
        Inches(11.5),
        Inches(0.8),
        size=28,
        bold=True,
        color=DARK,
    )


def add_bullet_list(slide, bullets, x, y, w, h):
    box = slide.shapes.add_textbox(x, y, w, h)

    tf = box.text_frame
    tf.clear()
    tf.word_wrap = True

    for i, bullet in enumerate(bullets[:5]):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()

        p.text = str(bullet)
        p.level = 0
        p.font.name = "Aptos"
        p.font.size = Pt(20)
        p.font.color.rgb = DARK
        p.space_after = Pt(16)

        p.text = "• " + p.text

    return box


def add_card(slide, x, y, w, h):
    card = slide.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE,
        x,
        y,
        w,
        h,
    )

    card.fill.solid()
    card.fill.fore_color.rgb = WHITE
    card.line.color.rgb = LIGHT

    return card


def render_bullets(slide, data):
    bullets = data.get("bullets", [])

    add_bullet_list(
        slide,
        bullets,
        Inches(1.0),
        Inches(1.65),
        Inches(11.2),
        Inches(4.9),
    )


def render_two_column(slide, data):
    add_card(
        slide,
        Inches(0.75),
        Inches(1.55),
        Inches(5.85),
        Inches(4.9),
    )

    add_card(
        slide,
        Inches(6.75),
        Inches(1.55),
        Inches(5.85),
        Inches(4.9),
    )

    add_text(
        slide,
        data.get("left_title", "Left"),
        Inches(1.05),
        Inches(1.9),
        Inches(5.1),
        Inches(0.5),
        size=21,
        bold=True,
        color=ACCENT,
    )

    add_text(
        slide,
        data.get("right_title", "Right"),
        Inches(7.05),
        Inches(1.9),
        Inches(5.1),
        Inches(0.5),
        size=21,
        bold=True,
        color=ACCENT,
    )

    add_bullet_list(
        slide,
        data.get("left", []),
        Inches(1.05),
        Inches(2.55),
        Inches(5.0),
        Inches(3.3),
    )

    add_bullet_list(
        slide,
        data.get("right", []),
        Inches(7.05),
        Inches(2.55),
        Inches(5.0),
        Inches(3.3),
    )


def render_stats(slide, data):
    stats = data.get("stats", [])[:4]

    count = max(len(stats), 1)
    card_w = 2.7
    gap = 0.35

    total = count * card_w + (count - 1) * gap
    start_x = (13.333 - total) / 2

    for i, stat in enumerate(stats):
        x = Inches(start_x + i * (card_w + gap))

        add_card(
            slide,
            x,
            Inches(2.0),
            Inches(card_w),
            Inches(3.4),
        )

        add_text(
            slide,
            stat.get("value", ""),
            x + Inches(0.2),
            Inches(2.55),
            Inches(card_w - 0.4),
            Inches(0.9),
            size=32,
            bold=True,
            color=ACCENT,
            align=PP_ALIGN.CENTER,
        )

        add_text(
            slide,
            stat.get("label", ""),
            x + Inches(0.2),
            Inches(3.55),
            Inches(card_w - 0.4),
            Inches(1.1),
            size=16,
            color=MUTED,
            align=PP_ALIGN.CENTER,
        )


def render_quote(slide, data):
    quote = data.get("quote", "")
    source = data.get("source", "")

    add_card(
        slide,
        Inches(1.2),
        Inches(1.65),
        Inches(10.9),
        Inches(4.6),
    )

    add_text(
        slide,
        "“",
        Inches(1.7),
        Inches(2.0),
        Inches(1.0),
        Inches(1.0),
        size=55,
        bold=True,
        color=ACCENT,
    )

    add_text(
        slide,
        quote,
        Inches(2.0),
        Inches(2.45),
        Inches(9.3),
        Inches(2.0),
        size=26,
        bold=True,
        color=DARK,
        align=PP_ALIGN.CENTER,
    )

    if source:
        add_text(
            slide,
            source,
            Inches(2.0),
            Inches(4.85),
            Inches(9.3),
            Inches(0.5),
            size=15,
            color=MUTED,
            align=PP_ALIGN.CENTER,
        )


def render_content_slide(slide, data, number):
    add_background(slide)
    add_top_accent(slide)
    add_title(slide, data.get("title", "Untitled"))

    layout = data.get("layout", "bullets")

    if layout == "two_column":
        render_two_column(slide, data)

    elif layout == "stats":
        render_stats(slide, data)

    elif layout == "quote":
        render_quote(slide, data)

    else:
        render_bullets(slide, data)

    add_footer(slide, number)


# =========================================================
# PRESENTATION
# =========================================================

def build_pptx(presentation_data: dict, output_path: str) -> str:
    prs = Presentation()

    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    # Remove default slide if one exists.
    while len(prs.slides):
        r_id = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(r_id)
        del prs.slides._sldIdLst[0]

    title = presentation_data.get("title", "Presentation")
    subtitle = presentation_data.get(
        "subtitle",
        "AI-generated presentation"
    )

    # -----------------------------------------------------
    # TITLE SLIDE
    # -----------------------------------------------------

    slide = prs.slides.add_slide(prs.slide_layouts[6])

    add_background(slide)

    accent = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        0,
        0,
        Inches(0.22),
        SLIDE_H,
    )

    accent.fill.solid()
    accent.fill.fore_color.rgb = ACCENT
    accent.line.fill.background()

    add_text(
        slide,
        title,
        Inches(1.05),
        Inches(2.05),
        Inches(10.8),
        Inches(1.6),
        size=38,
        bold=True,
        color=DARK,
    )

    add_text(
        slide,
        subtitle,
        Inches(1.08),
        Inches(3.75),
        Inches(9.8),
        Inches(1.0),
        size=20,
        color=MUTED,
    )

    # Decorative block
    block = slide.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE,
        Inches(10.75),
        Inches(5.3),
        Inches(1.45),
        Inches(0.7),
    )

    block.fill.solid()
    block.fill.fore_color.rgb = ACCENT
    block.line.fill.background()

    add_text(
        slide,
        "AI",
        Inches(10.75),
        Inches(5.43),
        Inches(1.45),
        Inches(0.35),
        size=18,
        bold=True,
        color=WHITE,
        align=PP_ALIGN.CENTER,
    )

    # -----------------------------------------------------
    # CONTENT SLIDES
    # -----------------------------------------------------

    slides = presentation_data.get("slides", [])

    for index, slide_data in enumerate(slides, start=2):
        slide = prs.slides.add_slide(prs.slide_layouts[6])

        if not isinstance(slide_data, dict):
            continue

        render_content_slide(
            slide,
            slide_data,
            index,
        )

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    prs.save(str(output))

    return str(output)
